### ISSUE TITLE
Switch from Hexbins to Census Tracts

### ISSUE THREAD

**Issue by johnclary** [cityofaustin/atd-dockless-dataviz#103]
As discussed [here](https://github.com/cityofaustin/atd-dockless-processing/issues/6), we're switching from hexbin aggregation to census tracts.

The app needs to be updated to display and query for census tract origins/destinations instead of hexbins. Dependent on the API being updated via [this issue](https://github.com/cityofaustin/atd-dockless-api/issues/48)

**Comment by johnclary** [comment]
@mateoclarke i **think** dockless-dataviz will just work once we update the API to return census tracts via this PR: https://github.com/cityofaustin/atd-dockless-api/pull/49.

**Comment by mateoclarke** [comment]
Now that the API code update is deployed, it looks like you were right @johnclary. The new polygon shapes come down with the API. I don't love the way it looks and there's a bug with the section color highlighting click that I'm going to log in a separate issue.

Here's what April's downtown data looks like with the default zoom and then zoomed way out. I wonder how useful this is and if we need to revisit scaling the height again.

### more or less default zoom

![Screen Shot 2019-04-30 at 4 49 43 PM](https://user-images.githubusercontent.com/5697474/56995703-14212c80-6b68-11e9-89a2-24ce3127c3fa.png)

### zoomed way out

![Screen Shot 2019-04-30 at 4 49 20 PM](https://user-images.githubusercontent.com/5697474/56995717-1f745800-6b68-11e9-9152-7db58cdd2409.png)
