### ISSUE TITLE
Color highlighting on clicked cell is broken

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-dockless-dataviz#105]
With the new json layer of census tracts coming from the dockless-api instead of hexbins, the color highlighting feature is now broken...

![Apr-30-2019 17-04-59](https://user-images.githubusercontent.com/5697474/56996421-200dee00-6b6a-11e9-8bd6-04ab05d952ef.gif)

**Comment by mateoclarke** [comment]
@johnclary Yeah, that makes sense. We are planning to go back to having hexbins at one point in the near future, right? We just need to play around with sizing? If so, I think we should update the API side and leave the JS code as is.

**Comment by johnclary** [comment]
Agreed. Here's that issue: https://github.com/cityofaustin/atd-dockless-api/issues/52

**Comment by johnclary** [comment]
@mateoclarke API has been updated. this should be resolved.

**Comment by mateoclarke** [comment]
Yup!

<img width="1552" alt="Screen Shot 2019-05-07 at 12 01 15 PM" src="https://user-images.githubusercontent.com/5697474/57318373-d66c5880-70bf-11e9-95a0-fee0a2351bbf.png">
