### ISSUE TITLE
Add Mapbox Popups for hexes with trip statistics

### ISSUE THREAD

**Issue by dianamartin** [cityofaustin/atd-dockless-dataviz#57]
Mateo and I discussed this. We were concerned it might be too visually overwhelming, but i think as a viewer they'd want to see the numbers on the map too and not just on the side panel.

**Comment by johnclary** [comment]
We could do away with the info box in the side panel and use a pop-up that displays on click. I think I originally used the side panel because I was too lazy to figure out mapbox popups 😛 

Related, the map could use a legend. Added #59

**Comment by mateoclarke** [comment]
I think adding mapbox popups instead of relying on the side panel to display info is the way to go.
