### ISSUE TITLE
Feature Request: Crash Data

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/atd-dockless-dataviz#65]
- user reported crashes
- crash data

Austin Public Health would probably be the best source for this.

**Comment by mateoclarke** [comment]
- lawsuits?
- 311?

**Comment by tom-montgomery** [comment]
Maybe yall already know this, but there is crash data available from txdot on their CRIS database
https://cris.dot.state.tx.us/public/Query/app/public/welcome.

They have a unit type of 'motorized conveyance' which should include motorized dockless vehicles. They also have bicycle crash data. A quick search from last year has ~360 crashes of these types. Almost all include lat/lon

DEFINITIONS (CONTINUED)
1.7 Motorized Conveyance means smaller motorized vehicles such as pocket
bikes, go-carts, golf carts, riding lawn mowers, mini-racers, snowmobiles, swamp
buggies, or similar devices, while in transport under own power.

**Comment by johnclary** [comment]
Thanks @tom-montgomery. We're familiar with CRIS but I'm not sure if our staff new there was a vehicle type that might cover dockless. Will relay.
