### ISSUE TITLE
License Declaration Requested

### ISSUE THREAD

**Issue by d-wasserman** [cityofaustin/atd-dockless-dataviz#99]
Hi , 

This seems like a pretty awesome project to use an an example for OD analysis generally. Can you please declare a license for the project such as Apache 2.0 or some other? 

Related links:
[Stack overlflow - Add License to Github Project](https://stackoverflow.com/questions/31639059/how-to-add-license-to-an-existing-github-project)
[License Guide - Choose A License](https://choosealicense.com/)
[Github Documentation](https://help.github.com/articles/licensing-a-repository/)
Thanks!

**Comment by johnclary** [comment]
Thanks @d-wasserman. Our typical approach is to add this to the readme:


> ## License
> 
> As a work of the City of Austin, this project is in the public domain within the United States.
>
> Additionally, we waive copyright and related rights in the work worldwide through the [CC0 1.0 Universal public domain dedication](https://creativecommons.org/publicdomain/zero/1.0/).

Curious if you have opinions about this and what other public agencies do in the U.S.

**Comment by d-wasserman** [comment]
This works too. I did not see this in the read me. 

I recommend however leveraging GitHub's license tagging system as well. Not every project in the public sector does this, but it is a best practice for projects to make clear how it can be used and be seen easly. MTC in the Bay Area has similar examples to this one, but sometimes they add the License.MD/TXT file so they get GitHub tags like this. 
https://github.com/BayAreaMetro/fast-trips-project/blob/gh-pages/LICENSE

An example from one of my projects just has the TXT file and it gets the same tag. 

https://github.com/d-wasserman/flask-network-prioritization-template

Hope this helps.

**Comment by mateoclarke** [comment]
adding license info to the README and LICENSE files now in #106. Thanks for flagging this @d-wasserman
